smwu-aws-cloud-club/courseX-project

courseX-backend/scripts/pre-commit, courseX-backend/src/main/java/com/acc/courseX/entity/Course.java, courseX-backend/src/main/java/com/acc/courseX/entity/CourseSchedule.java, courseX-backend/src/main/java/com/acc/courseX/entity/Enrollment.java, courseX-backend/src/main/java/com/acc/courseX/entity/Major.java, courseX-backend/src/main/java/com/acc/courseX/entity/User.java, courseX-backend/src/main/java/com/acc/courseX/entity/enums/CourseType.java, courseX-backend/src/main/java/com/acc/courseX/entity/enums/Role.java
- 회의 결과에 따라 다음과 같이 엔티티를 추가/수정했습니다
1. Major 엔티티 추가
2. User 엔티티에 하위 필드 추가/삭제
- role: student, professor 추가
- major: 학생/교수 본전공 추가
- affiliationId: 학생/교수 학번 또는 교번 추가
- email 필드 삭제
3. Course 엔티티에 하위 필드 추가
- professor: 수업 담당 교수 추가
- courseType(major, general): 전공 수업, 교양 수업에 대한 타입 지정 추가
- closed #10
=> [Feat/#10] Major 엔티티 추가 및 기존 엔티티 필드 추가

.github/workflows/main-CI.yml, courseX-backend/src/test/java/com/acc/courseX/CourseXApplicationTests.java
- 코드 통합 과정에 문제가 없는지 검증하기 위하여 CI 플로우를 구현했습니다
- test 실행 시 test.env 파일의 환경 변수를 사용하도록 설정해주었습니다
- closed #2
=> [Feat/#2] main 브랜치에 대한 CI 플로우 구현

.github/workflows/main-CI.yml, course-x-frontend/public/index.html, course-x-frontend/src/components/navbar.jsx
- Navbar의 클래스 네임을 가독성 높게 수정했습니다.
- closed #16
=> [Refactor/#16] Navbar 클래스네임 가독성 높이기

course-x-frontend/src/components/info.module.css, course-x-frontend/src/components/navbar.module.css, course-x-frontend/src/mock/course.json
- 아래로 스크롤해도 Navbar와 Info 컴포넌트가 계속 따라올 수 있도록 position을 sticky로 변경했습니다.
- closed #19
https://github.com/user-attachments/assets/62108860-6c8d-4b80-a54d-c6b70e8e7371
=> [Style/#19] Navbar와 Info 컴포넌트 position: sticky로 변경

.github/workflows/main-CI.yml, course-x-frontend/public/index.html, course-x-frontend/src/components/searchbar.jsx, course-x-frontend/src/page/EnrollPage.jsx
- searchParams 필드명을 q에서 code로 수정합니다.
- lint 경고가 빌드 실패로 이어지지 않도록 frontend ci 스크립트 수정했습니다.
- closed #21
=> [Modify/#21] searchParams 필드이름 code로 수정

course-x-frontend/.gitignore, course-x-frontend/package-lock.json, course-x-frontend/package.json, course-x-frontend/public/mockServiceWorker.js, course-x-frontend/src/api/course.js, course-x-frontend/src/axios.js, course-x-frontend/src/components/button.jsx, course-x-frontend/src/components/button.module.css, course-x-frontend/src/components/searchbar.jsx, course-x-frontend/src/index.js, course-x-frontend/src/mock/browser.js, course-x-frontend/src/mock/course.json, course-x-frontend/src/mock/handlers.js, course-x-frontend/src/page/CancelPage.module.css, course-x-frontend/src/page/EnrollPage.jsx, course-x-frontend/src/page/EnrollPage.module.css, course-x-frontend/src/route.js
- 수강신청 API 연결 작업했습니다.
- API를 Mocking해서 잘 동작하는지 확인했습니다.
- closed #23
[API 명세서 - 수강신청](https://www.notion.so/haesa-snow/223f5046e0c6415db6f2ff50163dd945?pvs=4)
=> [Feat/#23] 수강신청 API 연결

course-x-frontend/src/api/course.js, course-x-frontend/src/mock/handlers.js, course-x-frontend/src/page/EnrollPage.jsx
- 강의 목록 조회 API 연결 작업했습니다.
- API Mocking 후 잘 동작하는 걸 확인했습니다.
- closed #24
[API 명세서 - 수강 목록 조회](https://www.notion.so/haesa-snow/81d87c4c740043079364bcaee7fac0f7?pvs=4)
=> #24 [FEAT] 강의 목록 조회 API 연결

course-x-frontend/src/App.module.css, course-x-frontend/src/api/course.js, course-x-frontend/src/components/info.module.css, course-x-frontend/src/mock/handlers.js, course-x-frontend/src/page/CancelPage.jsx
- 수강 신청 내역 조회 API 연결 작업했습니다.
- API를 mocking 하여 의도대로 동작하는지 확인했습니다.
- closed #25
[API 명세서 - 수강 신청 내역 조회](https://www.notion.so/haesa-snow/3fb8f9b2b93e4e7d9bc182158685fc83?pvs=4)
=> [Feat/#25] 수강 신청 내역 조회 API 연결

course-x-frontend/src/api/course.js, course-x-frontend/src/mock/handlers.js, course-x-frontend/src/page/CancelPage.jsx
- 수강 취소 API 연결 작업했습니다.
- API를 mocking 하여 의도대로 동작하는지 확인했습니다.
- closed #26
[API 명세서 - 수강 취소](https://www.notion.so/haesa-snow/cfe56a858a394c6b878c6605b339ccba?pvs=4)
=> [Feat/#26] 수강 취소 API 연결

courseX-backend/src/main/java/com/acc/courseX/course/repository/CourseRepository.java, courseX-backend/src/main/java/com/acc/courseX/course/repository/CourseScheduleRepository.java, courseX-backend/src/main/java/com/acc/courseX/course/service/CourseServiceImpl.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/code/EnrollmentSuccess.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/controller/EnrollmentApi.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/controller/EnrollmentController.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/dto/EnrollmentResponse.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/repository/EnrollmentRepository.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/service/EnrollmentService.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/service/EnrollmentServiceImpl.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/validator/AbstractEnrollmentValidator.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/validator/GeneralCourseEnrollmentValidator.java, courseX-backend/src/main/java/com/acc/courseX/enrollment/validator/MajorCourseEnrollmentValidator.java
- 사용자가 수강 신청한 목록을 조회하는 API를 구현했습니다
- 사용자가 수강 신청을 철회한 내역은 조회되지 않습니다
- fetch join을 적용하여 N+1 문제를 방지했습니다
- 수강 신청을 취소한 강의에 대해 수강신청을 할 수 없는 문제를 수정했습니다
- closed #5
=> [Feat/#5] 수강 신청 목록 조회 API 구현

course-x-frontend/src/api/course.js, course-x-frontend/src/axios.js
- 인증 정보가 필요한 axios 객체에 X-USER-ID 커스텀 헤더를 추가했습니다.
- closed #35
=> [Feat/#35] authAxios에 로그인 헤더 설정

course-x-frontend/src/api/course.js, course-x-frontend/src/page/CancelPage.jsx, course-x-frontend/src/page/EnrollPage.jsx
API 응답에 문제가 발생하는 경우 기본값을 넘겨주어 참조 오류가 발생하는 문제를 해결했습니다.
- closed #38
=> [Fix/#38]: API 응답 오류 시 기본값을 전달해서 참조 오류 방지

.github/workflows/main-CD.yml, Docker/docker-compose.yml, Docker/nginx/conf.d/default.conf, Docker/nginx/nginx.conf, Docker/scripts/deploy.sh, courseX-backend/Dockerfile
main 브랜치에 머지될 때 Docker로 EC2에 배포될 수 있도록 CD 플로우를 구현했습니다.
- closed #37 
제가 Springboot는 CORS 에러를 어디서 해결하는지 몰라 건드리지 못했습니다. 해당 부분만 수정하면 프론트엔드와도 바로 연결이 될 것 같습니다.
=> [Feat/#37] main 브랜치에 대한 CD 플로우 구현

.github/workflows/main-CD.yml
기존에 Github Secret에 존재하던 ENV_FILE을 경로로 넣었는데, 해당 Secret에 무슨 내용이 적혀있는지 확인할 수 없어 CD를 위한 PROD_ENV_FILE을 Secret에 추가하고 경로를 수정했습니다.
- closed #44
=> [FIX] CD 파이프라인 에러 해결

courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
backend의 main cd가 잘 동작하는지 테스트합니다.
- closed #46
=> [TEST] backend main cd 동작 테스트

.github/workflows/main-CD.yml, courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
- #46 backend main cd가 제대로 동작하는지 테스트합니다.
=> [TEST] backend main cd 동작 테스트 2회차

course-x-frontend/src/index.js
React Query의 retry 설정을 껐습니다.
- closed #50
=> [Chore/#50] React Query retry 설정 끄기

courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java, docker/docker-compose.yml
백엔드에 https를 연결하여 CORS 에러를 해결했습니다.
- closed #46
=> [FIX] https 연결

course-x-frontend/src/api/course.js
엔드포인트에서 `/api` 제거
- closed #54
=> [Fix/#54]: 엔드포인트에서 /api 제거

.github/workflows/main-CD.yml, courseX-backend/deploy/scripts/deploy.sh
- prod.env 복사 경로를 수정합니다
- closed #64
=> fix: cd 플로우에서 env 파일 복사 로직 분리

courseX-backend/src/main/resources/application-prod.yaml
Nginx 문제를 해결하기 위해 application-prod.yaml 파일을 추가했습니다.
- closed #72
=> fix: application-prod.yaml 추가

courseX-backend/Dockerfile, courseX-backend/deploy/deploy.sh
health check가 EC2 -> docker로 실행되어 health check가 실패하는 문제를 해결했습니다.
- closed #72
=> fix: 컨테이너 내부에서 health check를 실행하도록 파일 변경

courseX-backend/Dockerfile
Dockerfile에서 curl 명령어 사용을 위해 Dockerfile 명령어 순서를 변경했습니다.
- closed #72
=> fix: 명령어 순서 변경

courseX-backend/deploy/deploy.sh
dockerfile 재빌드를 위한 트리거
- closed #72
=> test: dockerfile 재빌드를 위한 트리거

.github/workflows/main-CD.yml, courseX-backend/deploy/deploy.sh
docker에 curl 명령어를 설치하기 위해 Dockerfile을 수정했는데, cache 때문에 반영되지 않아 no cache 옵션을 추가했습니다.
- closed #72
=> fix: docker에 no cache 옵션 추가

.github/workflows/main-CD.yml, courseX-backend/deploy/deploy.sh
backend 변경 사항을 감지하였으나 build가 감지되지 않아 Revert 실행
- closed #72
=> Revert "fix: docker에 no cache 옵션 추가"

courseX-backend/deploy/deploy.sh
컨테이너 내부에서 curl을 사용하는 대신, Docker 호스트에서 직접 컨테이너의 헬스 체크 엔드포인트에 접근하는 방식으로 변경했습니다.
- closed #72
=> fix: health check 방식 변경

courseX-backend/src/main/resources/application-prod.yaml
잘못 작성되어 있던 application-local.yaml 파일의 내용을 변경했습니다.
- closed #72
=> fix: application-local.yaml 파일 변경

courseX-backend/src/main/resources/application-prod.yaml
actuator 경로를 /course-x-actuator 에서 /actuator로 변경했습니다.
- closed #72
=> fix: actuator 변경

courseX-backend/src/main/resources/jpa.yaml
jpa.yaml에 prod를 추가했습니다.
- closed #72
=> fix: jpa.yaml에 prod 추가

.github/workflows/main-CD.yml, courseX-backend/deploy/deploy.sh, courseX-backend/deploy/docker-compose.yml
docker의 image tag를 전부 latest로 변경했습니다.
- closed #72
=> fix: image tag를 latest로 변경

courseX-backend/deploy/deploy.sh
오류 발생 시 스크립트 예외처리 문구가 출력되지 않고 바로 스크립트가 종료되는 문제를 해결했습니다
- closed #88
=> [Fix/#88] deploy.sh에 오류가 발생할 수 있는 명령어에 || true 조건 추가
